<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerServiceSeeder extends Seeder
{
    public function run()
    {
        // Seed data for the 'customer_services' table
        $data = array (
  0 => 
  array (
    'id' => 66,
    'solution_id' => 117,
    'title' => 'Data Center Modernization',
    'label' => 'withImage',
    'description' => 'Unlock the full potential of your data center with virtualization, consolidation, and optimization strategies that maximize efficiency.',
    'image' => 'upload/customer_services/EcypBTMK4YGdUaVjjKLhhH0Ed4PNuiNidkY0wbF6.png',
    'deleted_at' => '2025-11-24 09:18:37',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:18:37',
  ),
  1 => 
  array (
    'id' => 67,
    'solution_id' => 117,
    'title' => 'Cloud Enablement',
    'label' => 'withImage',
    'description' => 'Make the leap to cloud with confidence. Our cloud enablement services guide you through migration planning, hybrid cloud architecture design, and virtual desktop implementation.',
    'image' => 'upload/customer_services/7pvQ4KmtZMsjfbwJnuIFgir9MEKMjkGPhPLYB0sh.png',
    'deleted_at' => '2025-11-24 09:18:37',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:18:37',
  ),
  2 => 
  array (
    'id' => 68,
    'solution_id' => 117,
    'title' => 'Business Continuity Modernization',
    'label' => 'withoutImage',
    'description' => 'Prepare for the unexpected with integrated Business Continuity and Disaster Recovery (BCDR) systems designed to protect your operations. We assess risks, design resilient architectures, and implement automated recovery solutions.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 09:18:37',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:18:37',
  ),
  3 => 
  array (
    'id' => 69,
    'solution_id' => 117,
    'title' => 'Process Integration Platforms',
    'label' => 'withoutImage',
    'description' => 'Break down silos and create digital continuity across your organization. Our process integration platforms connect systems, automate workflows, and ensure seamless data flow between departments.php artisan migrate:fresh --seed --seeder=CustomerServiceSeeder
',
    'image' => NULL,
    'deleted_at' => '2025-11-24 09:18:37',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:18:37',
  ),
  4 => 
  array (
    'id' => 70,
    'solution_id' => 117,
    'title' => 'Data Center Modernization',
    'label' => 'withImage',
    'description' => 'Unlock the full potential of your data center with virtualization, consolidation, and optimization strategies that maximize efficiency. We help you reduce physical footprint, lower operational costs, and improve resource utilization through server and storage virtualization turning complex legacy systems into streamlined, high-performance infrastructure that supports your growth.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 09:19:24',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:19:24',
  ),
  5 => 
  array (
    'id' => 71,
    'solution_id' => 117,
    'title' => 'Cloud Enablement',
    'label' => 'withImage',
    'description' => 'Make the leap to cloud with confidence. Our cloud enablement services guide you through migration planning, hybrid cloud architecture design, and virtual desktop implementation. Whether you\'re moving workloads to public, private, or hybrid environments, we ensure smooth transitions with security, scalability, and business continuity built in from day one.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 09:19:24',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:19:24',
  ),
  6 => 
  array (
    'id' => 72,
    'solution_id' => 117,
    'title' => 'Business Continuity Modernization',
    'label' => 'withImage',
    'description' => 'Prepare for the unexpected with integrated Business Continuity and Disaster Recovery (BCDR) systems designed to protect your operations. We assess risks, design resilient architectures, and implement automated recovery solutions that minimize downtime and data loss so your business stays operational even during disruptions, keeping stakeholders confident and operations uninterrupted.',
    'image' => 'upload/customer_services/1XnxVvaTRcOFqWB3MAl40vDUCickCNS24IQy9QoN.png',
    'deleted_at' => '2025-11-24 09:19:24',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:19:24',
  ),
  7 => 
  array (
    'id' => 73,
    'solution_id' => 117,
    'title' => 'Process Integration Platforms',
    'label' => 'withImage',
    'description' => 'Break down silos and create digital continuity across your organization. Our process integration platforms connect systems, automate workflows, and ensure seamless data flow between departments. By streamlining IT operations and enabling real-time collaboration, we help you eliminate inefficiencies, improve visibility, and create a unified digital ecosystem that works as one.',
    'image' => 'upload/customer_services/SGtMccCT9k3lcZCWKjhJsQZGsxM4382f19GZjC8f.png',
    'deleted_at' => '2025-11-24 09:19:24',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:19:24',
  ),
  8 => 
  array (
    'id' => 74,
    'solution_id' => 117,
    'title' => 'Data Center Modernization',
    'label' => 'withImage',
    'description' => 'Unlock the full potential of your data center with virtualization, consolidation, and optimization strategies that maximize efficiency.',
    'image' => 'upload/customer_services/DtiaC27m4bjYzGzsVJ5J85q32rlRSmkJTU4HlIhq.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  9 => 
  array (
    'id' => 75,
    'solution_id' => 117,
    'title' => 'Cloud Enablement',
    'label' => 'withImage',
    'description' => 'Make the leap to cloud with confidence. Our cloud enablement services guide you through migration planning, hybrid cloud architecture design, and virtual desktop implementation.',
    'image' => 'upload/customer_services/GKOArm4T5wrfeR4QkUefUdHhOc9vDqgIUMSZF3w1.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  10 => 
  array (
    'id' => 76,
    'solution_id' => 117,
    'title' => 'Business Continuity Modernization',
    'label' => 'withImage',
    'description' => 'Prepare for the unexpected with integrated Business Continuity and Disaster Recovery (BCDR) systems designed to protect your operations. We assess risks, design resilient architectures, and implement automated recovery solutions.',
    'image' => 'upload/customer_services/Pn6yFCzAmaKwfT0bfsJHFKYq1QstmzaHfxDn2G0U.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  11 => 
  array (
    'id' => 77,
    'solution_id' => 117,
    'title' => 'Process Integration Platforms',
    'label' => 'withImage',
    'description' => 'Break down silos and create digital continuity across your organization. Our process integration platforms connect systems, automate workflows, and ensure seamless data flow between departments.',
    'image' => 'upload/customer_services/V84LVUfE89zVnuAaP0bdKcTIXHQaDXF3cjGvQRyA.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  12 => 
  array (
    'id' => 78,
    'solution_id' => 118,
    'title' => 'Enterprise Architecture & Technology Roadmaps',
    'label' => 'withImage',
    'description' => 'Chart a clear path forward with enterprise architecture and technology roadmaps tailored to your business vision. We assess your current IT landscape, identify gaps and opportunities, and create strategic plans that guide technology evolution over time.',
    'image' => 'upload/customer_services/tnbf8456031xDtWi3lYRS32mVQ0IvP3JMcDF3jum.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  13 => 
  array (
    'id' => 79,
    'solution_id' => 118,
    'title' => 'Data Center Design & Implementation',
    'label' => 'withImage',
    'description' => 'Build data centers that combine physical robustness with logical excellence. From site selection and facility design to network topology and system configuration, we handle every aspect of data center creation and optimization.',
    'image' => 'upload/customer_services/xpZHo0MhprMcZCjOBC6iAf3pRryDD77cKhWw8Jod.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  14 => 
  array (
    'id' => 80,
    'solution_id' => 118,
    'title' => 'Database & Platform Optimization',
    'label' => 'withImage',
    'description' => 'Unlock better performance from your existing systems through expert optimization. We analyze database architectures, fine-tune configurations, and enhance resource utilization to eliminate bottlenecks and improve response times.',
    'image' => 'upload/customer_services/2vVc3bhkPdrh6CPGNEPl1B46aoaUNJ61iX7gdeQh.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  15 => 
  array (
    'id' => 81,
    'solution_id' => 118,
    'title' => 'System Integration & Infrastructure Management',
    'label' => 'withImage',
    'description' => 'Bring order to complexity with unified system integration and centralized infrastructure management. We connect disparate applications, platforms, and networks into cohesive ecosystems that communicate seamlessly.',
    'image' => 'upload/customer_services/br1QoYbXcFWWnLALbZ5zBxlFTt44I7knK4nJbijo.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  16 => 
  array (
    'id' => 82,
    'solution_id' => 118,
    'title' => 'Power Infrastructure for Mission-Critical ICT',
    'label' => 'withImage',
    'description' => 'Keep critical systems running with reliable power infrastructure designed for zero tolerance environments. We design and implement electrical systems, UPS configurations, generator setups, and redundant power architectures for data centers, control rooms, and telecom networks.',
    'image' => 'upload/customer_services/tEOT9AD7GZKgxDDbLofaTEmlg8gscSAqkL966AF8.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  17 => 
  array (
    'id' => 83,
    'solution_id' => 119,
    'title' => 'Network Security',
    'label' => 'withImage',
    'description' => 'Build a fortress around your digital infrastructure with comprehensive network security solutions. We deploy enterprise-grade firewalls, intrusion prevention and detection systems (IPS/IDS), secure gateways, and endpoint protection to create multiple defensive layers.',
    'image' => 'upload/customer_services/zy4oFVJOsSz3UPcc7zDcDgiANXIAGM5JwqFsOe4F.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  18 => 
  array (
    'id' => 84,
    'solution_id' => 119,
    'title' => 'Access Control & Identity Management',
    'label' => 'withImage',
    'description' => 'Control who accesses what, when, and how with intelligent identity and access management systems. We implement multi-factor authentication, role-based access controls, and zero-trust security models that verify every user and device before granting permissions.',
    'image' => 'upload/customer_services/1MTNEW4tlI54kvCqwNsDSMzDR6JNCSVxTqsrPYkL.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  19 => 
  array (
    'id' => 85,
    'solution_id' => 119,
    'title' => 'Data Security & Encryption',
    'label' => 'withImage',
    'description' => 'Protect your most valuable asset—your data—with military-grade encryption and security protocols. We secure sensitive information both at rest and in transit using advanced encryption standards, secure key management, and data loss prevention strategies.',
    'image' => 'upload/customer_services/O8uYuiFxreSNdwiI56KDZBXes7HgvCIZ9VBCQ1VM.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  20 => 
  array (
    'id' => 86,
    'solution_id' => 119,
    'title' => 'Compliance Frameworks',
    'label' => 'withImage',
    'description' => 'Navigate regulatory requirements with confidence through proven compliance framework implementation. We help you achieve and maintain certifications including ISO 27001, NADRA Verisys, GDPR readiness, and other global and local standards.',
    'image' => 'upload/customer_services/NDCbBkL5ZYCvl1iTKT89ZjF0fPZHIsr6dvdA26hw.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  21 => 
  array (
    'id' => 87,
    'solution_id' => 119,
    'title' => 'Security Audits & Vulnerability Assessments',
    'label' => 'withImage',
    'description' => 'Stay one step ahead of threats with proactive security audits and comprehensive vulnerability assessments. Our experts conduct thorough penetration testing, risk analysis, and security reviews to identify weaknesses before attackers do.',
    'image' => 'upload/customer_services/R6lGVPluDwx8ztD60M1f2d6nT20xlglL0lpA8T0r.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  22 => 
  array (
    'id' => 88,
    'solution_id' => 120,
    'title' => 'Compute & Storage Systems',
    'label' => 'withImage',
    'description' => 'Power your operations with enterprise-grade compute and storage solutions built for demanding workloads. We integrate high-performance servers, workstations, laptops, and scalable storage systems tailored to your business requirements.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 09:37:49',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:37:49',
  ),
  23 => 
  array (
    'id' => 89,
    'solution_id' => 120,
    'title' => 'Network Infrastructure – Active',
    'label' => 'withImage',
    'description' => 'Connect your enterprise with intelligent, high-performance active network infrastructure. We deploy and configure advanced switching, routing, Wi-Fi systems, and software-defined networking (SDN) solutions that optimize traffic flow and network performance.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 09:37:49',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:37:49',
  ),
  24 => 
  array (
    'id' => 90,
    'solution_id' => 120,
    'title' => 'Network Infrastructure – Passive',
    'label' => 'withImage',
    'description' => 'Build the foundation of reliable connectivity with professionally designed passive network infrastructure. We install structured cabling systems, patch panels, racks, enclosures, and cable management solutions that meet industry standards and best practices.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 09:37:49',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:37:49',
  ),
  25 => 
  array (
    'id' => 91,
    'solution_id' => 120,
    'title' => 'Power & Backup Systems',
    'label' => 'withImage',
    'description' => 'Eliminate downtime with robust power and backup systems designed for mission-critical environments. We design and implement UPS solutions, generator systems, and redundant power architectures for data centers, industrial facilities, and enterprise operations.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 09:37:49',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:37:49',
  ),
  26 => 
  array (
    'id' => 92,
    'solution_id' => 120,
    'title' => 'Peripherals & End-User Devices',
    'label' => 'withImage',
    'description' => 'Equip your workforce with the right tools for productivity and collaboration. We handle procurement and integration of peripherals and end-user devices including monitors, printers, scanners, conferencing equipment, and specialized hardware.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 09:37:49',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:37:49',
  ),
  27 => 
  array (
    'id' => 93,
    'solution_id' => 120,
    'title' => 'Compute & Storage Systems',
    'label' => 'withImage',
    'description' => 'Power your operations with enterprise-grade compute and storage solutions built for demanding workloads. We integrate high-performance servers, workstations, laptops, and scalable storage systems tailored to your business requirements.',
    'image' => 'upload/customer_services/FFPijeIrXFKb3OgfuzZtpwlSHGCXuBxqqfFHBpOz.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  28 => 
  array (
    'id' => 94,
    'solution_id' => 120,
    'title' => 'Network Infrastructure – Active',
    'label' => 'withImage',
    'description' => 'Connect your enterprise with intelligent, high-performance active network infrastructure. We deploy and configure advanced switching, routing, Wi-Fi systems, and software-defined networking (SDN) solutions that optimize traffic flow and network performance.',
    'image' => 'upload/customer_services/zvJlFWbe6b7I8H3kos8jAfEujguK1UZvQ2XLNOcG.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  29 => 
  array (
    'id' => 95,
    'solution_id' => 120,
    'title' => 'Network Infrastructure – Passive',
    'label' => 'withImage',
    'description' => 'Build the foundation of reliable connectivity with professionally designed passive network infrastructure. We install structured cabling systems, patch panels, racks, enclosures, and cable management solutions that meet industry standards and best practices.',
    'image' => 'upload/customer_services/HnsVzGfCEAfj3Ao970W3V6nM6E1QXpMaxtWjHohv.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  30 => 
  array (
    'id' => 96,
    'solution_id' => 120,
    'title' => 'Power & Backup Systems',
    'label' => 'withImage',
    'description' => 'Eliminate downtime with robust power and backup systems designed for mission-critical environments. We design and implement UPS solutions, generator systems, and redundant power architectures for data centers, industrial facilities, and enterprise operations.',
    'image' => 'upload/customer_services/778ntBXRpQvA9ulc1vl8P3IjPcLsGKeBuy40BUqL.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  31 => 
  array (
    'id' => 97,
    'solution_id' => 120,
    'title' => 'Peripherals & End-User Devices',
    'label' => 'withImage',
    'description' => 'Equip your workforce with the right tools for productivity and collaboration. We handle procurement and integration of peripherals and end-user devices including monitors, printers, scanners, conferencing equipment, and specialized hardware.',
    'image' => 'upload/customer_services/lxn1PuxtqvJiu7cV6w8RO3AZeg9DNVbgahFS6kwp.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  32 => 
  array (
    'id' => 98,
    'solution_id' => 121,
    'title' => 'Load & Performance Testing',
    'label' => 'withImage',
    'description' => 'Discover how your systems truly perform under pressure with comprehensive load and performance testing. We simulate real-world workloads, peak traffic scenarios, and stress conditions to evaluate system behavior, identify bottlenecks, and validate capacity limits.',
    'image' => 'upload/customer_services/LBhMspOi1LHpbMjrnCKbOt6gr9mg0BCyAlCQjmxJ.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  33 => 
  array (
    'id' => 99,
    'solution_id' => 121,
    'title' => 'High Availability / Failover Validation',
    'label' => 'withImage',
    'description' => 'Guarantee business continuity with rigorous high availability and failover testing for critical systems. We validate redundancy mechanisms, test automatic failover procedures, and verify that backup systems activate seamlessly during primary system failures.',
    'image' => 'upload/customer_services/WapTvKclaiKMYFqUWWdlDLusqsLui0CB8V6SeUh6.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  34 => 
  array (
    'id' => 100,
    'solution_id' => 121,
    'title' => 'BCDR Drills & Simulation Testing',
    'label' => 'withImage',
    'description' => 'Prepare for the unexpected with practical Business Continuity and Disaster Recovery drills that test your readiness. We conduct realistic simulations of disaster scenarios from system failures to complete site outages verifying that recovery procedures work, RTOs and RPOs are met, and teams know their roles.',
    'image' => 'upload/customer_services/oUsck8DY9A2dwfYRZ0DF3Nv6FFuIRztfx6obWu12.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  35 => 
  array (
    'id' => 101,
    'solution_id' => 121,
    'title' => 'QA for Software & System Integration Projects',
    'label' => 'withImage',
    'description' => 'Ensure seamless operation across complex, integrated environments with comprehensive QA for system integration projects. We validate data flows, API connections, cross-system functionality, and user workflows spanning multiple platforms and divisions.',
    'image' => 'upload/customer_services/NRQvxHD3FZ5QbKv6chJ6s35khhELrSfPGNBLdxOP.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  36 => 
  array (
    'id' => 102,
    'solution_id' => 122,
    'title' => 'e-Governance & Citizen Portals',
    'label' => 'withImage',
    'description' => 'Transform how governments connect with citizens through intuitive digital platforms that make services accessible anytime, anywhere. We design and implement comprehensive e-governance portals that enable online applications.',
    'image' => 'upload/customer_services/z43EbeTpLeMXlt7py4RLIqBPpGfSOXNfr3miKQ1x.png',
    'deleted_at' => '2025-11-24 09:48:28',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:48:28',
  ),
  37 => 
  array (
    'id' => 103,
    'solution_id' => 122,
    'title' => 'Licensing, Permitting & Utility Billing Systems',
    'label' => 'withImage',
    'description' => 'Automate complex licensing, permitting, and billing processes with intelligent management systems that eliminate manual bottlenecks.',
    'image' => 'upload/customer_services/eeQPMqjHLojp8oJ1F3g8yOLG8utdBQonkFsaUQ05.png',
    'deleted_at' => '2025-11-24 09:48:28',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:48:28',
  ),
  38 => 
  array (
    'id' => 104,
    'solution_id' => 122,
    'title' => 'Public Safety & Law Enforcement Systems',
    'label' => 'withImage',
    'description' => 'Strengthen community safety with intelligent information systems designed for rapid response and coordinated enforcement.',
    'image' => 'upload/customer_services/4Ywg3THK0fS9Fbhv9dIzvMIwdUSmT3fyfjMnEZgJ.png',
    'deleted_at' => '2025-11-24 09:48:28',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:48:28',
  ),
  39 => 
  array (
    'id' => 105,
    'solution_id' => 122,
    'title' => 'Tourism & Visitor Management Platforms',
    'label' => 'withImage',
    'description' => 'Elevate visitor experiences and streamline destination management with comprehensive tourism platforms. We create digital solutions for destination marketing, event management, booking systems, visitor information, and engagement analytics.',
    'image' => 'upload/customer_services/PJ8mo5vDqUke43WShkM5nkPiytVD9r1ohFTdHagr.png',
    'deleted_at' => '2025-11-24 09:48:28',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:48:28',
  ),
  40 => 
  array (
    'id' => 106,
    'solution_id' => 122,
    'title' => 'Transport & Traffic Management Systems',
    'label' => 'withImage',
    'description' => 'Optimize mobility and reduce congestion with intelligent transport and traffic management solutions. We implement systems for traffic monitoring, signal control, public transit management, fleet tracking, and logistics coordination.',
    'image' => 'upload/customer_services/cwIufcadcJyWmOSGkoeXuzgSnYXMJeB1Vab6XLll.png',
    'deleted_at' => '2025-11-24 09:48:28',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 09:48:28',
  ),
  41 => 
  array (
    'id' => 107,
    'solution_id' => 122,
    'title' => 'e-Governance & Citizen Portals',
    'label' => 'withImage',
    'description' => 'Transform how governments connect with citizens through intuitive digital platforms that make services accessible anytime, anywhere. We design and implement comprehensive e-governance portals that enable online applications.',
    'image' => 'upload/customer_services/YLwX7jHDEYs0A79LGztflB2q7pDoNegvWFVt1t8M.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  42 => 
  array (
    'id' => 108,
    'solution_id' => 122,
    'title' => 'Licensing, Permitting & Utility Billing Systems',
    'label' => 'withImage',
    'description' => 'Automate complex licensing, permitting, and billing processes with intelligent management systems that eliminate manual bottlenecks.',
    'image' => 'upload/customer_services/NuUCvpPUzDHvDOGuhnIXQALp9KABKc35h9ulonfu.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  43 => 
  array (
    'id' => 109,
    'solution_id' => 122,
    'title' => 'Public Safety & Law Enforcement Systems',
    'label' => 'withImage',
    'description' => 'Strengthen community safety with intelligent information systems designed for rapid response and coordinated enforcement.',
    'image' => 'upload/customer_services/ndl9EEXrdsVwMDm9PCFrNjZFdb6YReubObz4E0gg.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  44 => 
  array (
    'id' => 110,
    'solution_id' => 122,
    'title' => 'Tourism & Visitor Management Platforms',
    'label' => 'withImage',
    'description' => 'Elevate visitor experiences and streamline destination management with comprehensive tourism platforms. We create digital solutions for destination marketing, event management, booking systems, visitor information, and engagement analytics.',
    'image' => 'upload/customer_services/8K3adBnMrb1Me3uhLoVJv4OtywxKWDtyAz6co6mF.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  45 => 
  array (
    'id' => 111,
    'solution_id' => 122,
    'title' => 'Transport & Traffic Management Systems',
    'label' => 'withImage',
    'description' => 'Optimize mobility and reduce congestion with intelligent transport and traffic management solutions. We implement systems for traffic monitoring, signal control, public transit management, fleet tracking, and logistics coordination.',
    'image' => 'upload/customer_services/vpwTKdotIH5IyyZ3E3jlPykWHOuVPOSYRzdeoCub.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  46 => 
  array (
    'id' => 112,
    'solution_id' => 123,
    'title' => 'HR & Payroll Automation',
    'label' => 'withImage',
    'description' => 'Streamline workforce management with comprehensive HR and payroll systems that handle everything from recruitment to compensation.',
    'image' => 'upload/customer_services/37sCNFoTi8DpvUzKy0tA8WP6ZX5JP4AHOYmKc3iE.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  47 => 
  array (
    'id' => 113,
    'solution_id' => 123,
    'title' => 'Asset & Financial Management Systems',
    'label' => 'withImage',
    'description' => 'Gain complete control over your assets and finances with real-time tracking and management systems. We implement solutions that monitor asset lifecycles, track inventory, manage budgets, process expenditures, and generate financial reports, all from unified platforms.',
    'image' => 'upload/customer_services/1a8xKpEzUfwGkndJaFu0G4oxJ53OwzzH9QgeUo7J.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  48 => 
  array (
    'id' => 114,
    'solution_id' => 123,
    'title' => 'Event & Facility Management Systems',
    'label' => 'withImage',
    'description' => 'Coordinate events and manage facilities effortlessly with digital tools designed for operational excellence. Our platforms handle event planning, resource scheduling, venue management, catering coordination, and participant registration.',
    'image' => 'upload/customer_services/YyhUiLa7JLGrzAzX9WOxYMEOxFdlquhCGRzHtBiN.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  49 => 
  array (
    'id' => 115,
    'solution_id' => 123,
    'title' => 'Fleet & Mobility Management',
    'label' => 'withImage',
    'description' => 'Optimize your mobile assets with intelligent fleet and mobility management solutions. We develop comprehensive systems for vehicle tracking, route optimization, fuel monitoring, maintenance scheduling, and driver management.',
    'image' => 'upload/customer_services/9KCnibFofyqQY2bIKSPEDLcxD1PccHWhOehaIUlv.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  50 => 
  array (
    'id' => 116,
    'solution_id' => 123,
    'title' => 'Biometric & Time Attendance Systems',
    'label' => 'withImage',
    'description' => 'Ensure accurate workforce tracking with secure biometric and time attendance systems that integrate seamlessly with your HR platforms.',
    'image' => 'upload/customer_services/d9BdQfO5hnTvypDcbsKgBmB0y2QhHCHbz123wwlS.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  51 => 
  array (
    'id' => 122,
    'solution_id' => 124,
    'title' => 'AI Chatbots & Virtual Assistants',
    'label' => 'withImage',
    'description' => 'Transform customer engagement and lead qualification with intelligent chatbots and virtual assistants that understand context and deliver instant responses.',
    'image' => 'upload/customer_services/V2vWWoBUneuX4bpb0Mry1TH7ZBtacK0rjtYGRWbK.png',
    'deleted_at' => '2025-11-24 10:03:52',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:03:52',
  ),
  52 => 
  array (
    'id' => 128,
    'solution_id' => 124,
    'title' => 'AI Chatbots & Virtual Assistants',
    'label' => 'withImage',
    'description' => 'Transform customer engagement and lead qualification with intelligent chatbots and virtual assistants that understand context and deliver instant responses. ',
    'image' => 'upload/customer_services/P6X4vRpJWBSQ53XAwdv0QR6Y3ycUTs8ChdQXid0W.png',
    'deleted_at' => '2025-11-24 10:05:19',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:05:19',
  ),
  53 => 
  array (
    'id' => 129,
    'solution_id' => 124,
    'title' => 'Voice Agents & Conversational Interfaces',
    'label' => 'withImage',
    'description' => 'Enable natural, hands-free interactions with multilingual voice agents that understand and respond like humans.',
    'image' => 'upload/customer_services/DSeuJiGjoo6IuHUTcilvUCGbiMJGto7KTf5BIjKm.png',
    'deleted_at' => '2025-11-24 10:05:19',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:05:19',
  ),
  54 => 
  array (
    'id' => 130,
    'solution_id' => 124,
    'title' => 'AI Chatbots & Virtual Assistants',
    'label' => 'withImage',
    'description' => 'Transform customer engagement and lead qualification with intelligent chatbots and virtual assistants that understand context and deliver instant responses.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:05:54',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:05:54',
  ),
  55 => 
  array (
    'id' => 131,
    'solution_id' => 124,
    'title' => 'Voice Agents & Conversational Interfaces',
    'label' => 'withImage',
    'description' => 'Enable natural, hands-free interactions with multilingual voice agents that understand and respond like humans. ',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:05:54',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:05:54',
  ),
  56 => 
  array (
    'id' => 132,
    'solution_id' => 124,
    'title' => 'Analytics Dashboards',
    'label' => 'withImage',
    'description' => 'Turn data into strategic advantage with AI-powered analytics dashboards that deliver real-time insights at a glance.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:05:54',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:05:54',
  ),
  57 => 
  array (
    'id' => 133,
    'solution_id' => 124,
    'title' => 'AI Chatbots & Virtual Assistants',
    'label' => 'withImage',
    'description' => 'Transform customer engagement and lead qualification with intelligent chatbots and virtual assistants that understand context and deliver instant responses.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:06:40',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:06:40',
  ),
  58 => 
  array (
    'id' => 134,
    'solution_id' => 124,
    'title' => 'Voice Agents & Conversational Interfaces',
    'label' => 'withImage',
    'description' => 'Enable natural, hands-free interactions with multilingual voice agents that understand and respond like humans.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:06:40',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:06:40',
  ),
  59 => 
  array (
    'id' => 135,
    'solution_id' => 124,
    'title' => 'Analytics Dashboards',
    'label' => 'withImage',
    'description' => 'Turn data into strategic advantage with AI-powered analytics dashboards that deliver real-time insights at a glance.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:06:40',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:06:40',
  ),
  60 => 
  array (
    'id' => 136,
    'solution_id' => 124,
    'title' => 'RPA & Workflow Bots',
    'label' => 'withImage',
    'description' => 'Eliminate tedious manual work with Robotic Process Automation that handles repetitive, rule-based tasks with precision and speed. Our workflow bots automate data entry, document processing, report generation, system updates, and cross-application workflows working 24/7 without errors or fatigue.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:06:40',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:06:40',
  ),
  61 => 
  array (
    'id' => 147,
    'solution_id' => 124,
    'title' => 'AI Chatbots & Virtual Assistants',
    'label' => 'withImage',
    'description' => 'Transform customer engagement and lead qualification with intelligent chatbots and virtual assistants that understand context and deliver instant responses.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:08:42',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:08:42',
  ),
  62 => 
  array (
    'id' => 148,
    'solution_id' => 124,
    'title' => 'Voice Agents & Conversational Interfaces',
    'label' => 'withImage',
    'description' => 'Enable natural, hands-free interactions with multilingual voice agents that understand and respond like humans.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:08:42',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:08:42',
  ),
  63 => 
  array (
    'id' => 149,
    'solution_id' => 124,
    'title' => 'Analytics Dashboards',
    'label' => 'withImage',
    'description' => 'Turn data into strategic advantage with AI-powered analytics dashboards that deliver real-time insights at a glance. ',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:08:42',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:08:42',
  ),
  64 => 
  array (
    'id' => 150,
    'solution_id' => 124,
    'title' => 'RPA & Workflow Bots',
    'label' => 'withImage',
    'description' => 'Eliminate tedious manual work with Robotic Process Automation that handles repetitive, rule-based tasks with precision and speed. Our workflow bots automate data entry, document processing, report generation, system updates, and cross-application workflows working 24/7 without errors or fatigue.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:08:42',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:08:42',
  ),
  65 => 
  array (
    'id' => 151,
    'solution_id' => 124,
    'title' => 'AI Chatbots & Virtual Assistants',
    'label' => 'withImage',
    'description' => 'Transform customer engagement and lead qualification with intelligent chatbots and virtual assistants that understand context and deliver instant responses. ',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:09:17',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:09:17',
  ),
  66 => 
  array (
    'id' => 152,
    'solution_id' => 124,
    'title' => 'Voice Agents & Conversational Interfaces',
    'label' => 'withImage',
    'description' => 'Enable natural, hands-free interactions with multilingual voice agents that understand and respond like humans. ',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:09:17',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:09:17',
  ),
  67 => 
  array (
    'id' => 153,
    'solution_id' => 124,
    'title' => 'Analytics Dashboards',
    'label' => 'withImage',
    'description' => 'Turn data into strategic advantage with AI-powered analytics dashboards that deliver real-time insights at a glance. ',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:09:17',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:09:17',
  ),
  68 => 
  array (
    'id' => 154,
    'solution_id' => 124,
    'title' => 'RPA & Workflow Bots',
    'label' => 'withImage',
    'description' => 'Eliminate tedious manual work with Robotic Process Automation that handles repetitive, rule-based tasks with precision and speed. Our workflow bots automate data entry, document processing, report generation, system updates, and cross-application workflows working 24/7 without errors or fatigue.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:09:17',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:09:17',
  ),
  69 => 
  array (
    'id' => 155,
    'solution_id' => 124,
    'title' => 'aaa',
    'label' => 'withImage',
    'description' => 'xxxx',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:09:17',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:09:17',
  ),
  70 => 
  array (
    'id' => 161,
    'solution_id' => 124,
    'title' => 'AI Chatbots & Virtual Assistants',
    'label' => 'withImage',
    'description' => 'Transform customer engagement and lead qualification with intelligent chatbots and virtual assistants that understand context and deliver instant responses.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:10:15',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:10:15',
  ),
  71 => 
  array (
    'id' => 162,
    'solution_id' => 124,
    'title' => 'Voice Agents & Conversational Interfaces',
    'label' => 'withImage',
    'description' => 'Enable natural, hands-free interactions with multilingual voice agents that understand and respond like humans. ',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:10:15',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:10:15',
  ),
  72 => 
  array (
    'id' => 163,
    'solution_id' => 124,
    'title' => 'Analytics Dashboards',
    'label' => 'withImage',
    'description' => 'Turn data into strategic advantage with AI-powered analytics dashboards that deliver real-time insights at a glance.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:10:15',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:10:15',
  ),
  73 => 
  array (
    'id' => 164,
    'solution_id' => 124,
    'title' => 'RPA & Workflow Bots',
    'label' => 'withImage',
    'description' => 'Eliminate tedious manual work with Robotic Process Automation that handles repetitive, rule-based tasks with precision and speed. Our workflow bots automate data entry, document processing, report generation, system updates, and cross-application workflows working 24/7 without errors or fatigue.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:10:15',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:10:15',
  ),
  74 => 
  array (
    'id' => 165,
    'solution_id' => 124,
    'title' => 'Data-Driven Decision Support Systems',
    'label' => 'withImage',
    'description' => 'Enhance strategic planning with intelligent decision support systems that analyze complex data and provide actionable recommendations.',
    'image' => NULL,
    'deleted_at' => '2025-11-24 10:10:15',
    'created_at' => NULL,
    'updated_at' => '2025-11-24 10:10:15',
  ),
  75 => 
  array (
    'id' => 166,
    'solution_id' => 124,
    'title' => 'AI Chatbots & Virtual Assistants',
    'label' => 'withImage',
    'description' => 'Transform customer engagement and lead qualification with intelligent chatbots and virtual assistants that understand context and deliver instant responses. ',
    'image' => 'upload/customer_services/9zCCxgWudrnA2OPfgYsKuDJpwiFe0SGbBPtEcPNK.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  76 => 
  array (
    'id' => 167,
    'solution_id' => 124,
    'title' => 'Voice Agents & Conversational Interfaces',
    'label' => 'withImage',
    'description' => 'Enable natural, hands-free interactions with multilingual voice agents that understand and respond like humans.',
    'image' => 'upload/customer_services/IkYB7J1Qg2zvsG8U7sVxU7ebkIEpGMzc0cqVO4Bk.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  77 => 
  array (
    'id' => 168,
    'solution_id' => 124,
    'title' => 'Analytics Dashboards',
    'label' => 'withImage',
    'description' => 'Turn data into strategic advantage with AI-powered analytics dashboards that deliver real-time insights at a glance. ',
    'image' => 'upload/customer_services/a0LWAI7xqZw288k9YKclAzRwMw3lfJ7tlquInrXh.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  78 => 
  array (
    'id' => 169,
    'solution_id' => 124,
    'title' => 'RPA & Workflow Bots',
    'label' => 'withImage',
    'description' => 'Eliminate tedious manual work with Robotic Process Automation that handles repetitive, rule-based tasks with precision and speed. Our workflow bots automate data entry, document processing, report generation, system updates, and cross-application workflows working 24/7 without errors or fatigue.',
    'image' => 'upload/customer_services/sME9AvwnoylGlKN2TTB5KkLaGEeCtKtixmF2QgzP.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  79 => 
  array (
    'id' => 170,
    'solution_id' => 124,
    'title' => 'Data-Driven Decision Support Systems',
    'label' => 'withImage',
    'description' => 'Enhance strategic planning with intelligent decision support systems that analyze complex data and provide actionable recommendations.',
    'image' => 'upload/customer_services/FXgMU7mubF9BV08NjXhRn9UWrAdFearJk5fnZWsE.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  80 => 
  array (
    'id' => 171,
    'solution_id' => 125,
    'title' => 'Web & Mobile App Development',
    'label' => 'withImage',
    'description' => 'Bring your vision to life with modern web and mobile applications designed for exceptional user experiences. We develop responsive, high-performance platforms for businesses and governments that combine beautiful design with robust functionality.',
    'image' => 'upload/customer_services/8WU6kfGXJpbyvvQUe0DAaH7Pz6efFFy7KyN48R2Z.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  81 => 
  array (
    'id' => 172,
    'solution_id' => 125,
    'title' => 'Custom Portals, Dashboards & CRMs',
    'label' => 'withImage',
    'description' => 'Empower your organization with tailored interfaces that centralize operations, analytics, and customer relationships. We design and develop custom portals for stakeholder engagement, real-time dashboards for data visualization.',
    'image' => 'upload/customer_services/OcfVzthzcAHcJ9P3EvQYM3LvJsq4TMlk5phx4HRL.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  82 => 
  array (
    'id' => 173,
    'solution_id' => 125,
    'title' => 'API Integrations & Cloud-Native Applications',
    'label' => 'withImage',
    'description' => 'Break down silos and enable seamless workflows with robust API integrations and cloud-native applications. We connect disparate systems, enable real-time data exchange, and build applications that leverage cloud scalability and resilience.',
    'image' => 'upload/customer_services/LWZamkuwvpk7lkJnyhrF90D1VPWodyE1Z05Si47P.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  83 => 
  array (
    'id' => 174,
    'solution_id' => 125,
    'title' => 'Multi-Platform Mobile Solutions',
    'label' => 'withImage',
    'description' => 'Reach users wherever they are with native and hybrid mobile applications for iOS, Android, and cross-platform environments. We develop enterprise mobile solutions and public-facing apps that deliver consistent experiences.',
    'image' => 'upload/customer_services/1CT4q8XBRx9uuDJjnqRefx5kIh3X2xPLv3MYweqb.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  84 => 
  array (
    'id' => 175,
    'solution_id' => 126,
    'title' => 'River Flow & Discharge Monitoring',
    'label' => 'withImage',
    'description' => 'Track river behavior with precision through automated flow and discharge monitoring systems that provide real-time insights into water movement.',
    'image' => 'upload/customer_services/KIV6sfn5ID3QPAUibLeAciorY2RDjOEG8oU8B0BZ.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  85 => 
  array (
    'id' => 176,
    'solution_id' => 126,
    'title' => 'Flood Forecasting & Early Warning Systems',
    'label' => 'withImage',
    'description' => 'Save lives and protect infrastructure with intelligent flood forecasting and early warning systems that predict inundation before it happens.',
    'image' => 'upload/customer_services/bGm1oLa1GdvCWkm8zYjmppWoSVcGqBNazihfYaAs.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  86 => 
  array (
    'id' => 177,
    'solution_id' => 126,
    'title' => 'Urban Hydrology & Stormwater Solutions',
    'label' => 'withImage',
    'description' => 'Manage urban water challenges with intelligent stormwater monitoring and drainage solutions designed for modern cities. We implement systems that track rainfall intensity, monitor drainage capacity.',
    'image' => 'upload/customer_services/si7Zp9m6xSwDobtRO8s14afqXOoahZQ8WmLucJi2.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  87 => 
  array (
    'id' => 178,
    'solution_id' => 126,
    'title' => 'Groundwater & Surface Water Monitoring',
    'label' => 'withImage',
    'description' => 'Ensure sustainable water resource management with comprehensive groundwater and surface water monitoring systems. We deploy sensor networks that track water table levels, aquifer recharge rates.',
    'image' => 'upload/customer_services/AyBkgVMJLvwWkBvEZxnWNj4IUW7ca3FYCC9hyiTr.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  88 => 
  array (
    'id' => 179,
    'solution_id' => 127,
    'title' => 'Weather Stations',
    'label' => 'withImage',
    'description' => 'Deploy specialized weather stations designed for mission-critical applications where precision matters. Our traffic weather systems monitor road surface conditions, visibility, and precipitation.',
    'image' => 'upload/customer_services/T183yIJm18Jt9dgSPhrGcRxdW3g5T2ymMLrap37w.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  89 => 
  array (
    'id' => 180,
    'solution_id' => 127,
    'title' => 'Hydro-Meteorological Networks',
    'label' => 'withImage',
    'description' => 'Build comprehensive monitoring coverage with integrated hydro-meteorological networks that combine weather and water observations.',
    'image' => 'upload/customer_services/4xLZDDuCI63xBq6CL2lYjfJ101YtRaJ6ed0C6wGh.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  90 => 
  array (
    'id' => 181,
    'solution_id' => 127,
    'title' => 'Solar Radiation & Energy Resource Monitoring',
    'label' => 'withImage',
    'description' => 'Optimize renewable energy production with precise solar radiation and meteorological resource monitoring.',
    'image' => 'upload/customer_services/seVfNRbllRlwpZPKFCCUD3ws5l31PRsYat9cId6H.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  91 => 
  array (
    'id' => 182,
    'solution_id' => 128,
    'title' => 'Groundwater / Surface Water Quality',
    'label' => 'withImage',
    'description' => 'Safeguard drinking water sources and aquatic ecosystems with comprehensive groundwater and surface water quality monitoring.',
    'image' => 'upload/customer_services/9OOW7BW1SnisiiAZlQDVcOmp5r3JZ28aFpZyAAx9.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  92 => 
  array (
    'id' => 183,
    'solution_id' => 128,
    'title' => 'Reservoir & Lake Profiling',
    'label' => 'withImage',
    'description' => 'Optimize water supply management and protect aquatic health through detailed reservoir and lake profiling. Our monitoring systems track vertical water column profiles, measuring temperature stratification, dissolved oxygen levels, nutrient concentrations, algae populations, and other parameters at multiple depths.',
    'image' => 'upload/customer_services/fvTj0hRzQ4ixqg8lU1u86erlu0vuOfDYCnF8tVIh.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  93 => 
  array (
    'id' => 184,
    'solution_id' => 128,
    'title' => 'Agricultural Runoff & Wetland Monitoring',
    'label' => 'withImage',
    'description' => 'Protect downstream water quality and wetland ecosystems by monitoring agricultural runoff and wetland health. We implement monitoring stations that track nutrient loads, pesticide residues, sediment transport, and water quality.',
    'image' => 'upload/customer_services/pXkU4TNl5pFMOlMMi66Cc8uw8XTJR2U7MojSlWgW.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  94 => 
  array (
    'id' => 185,
    'solution_id' => 128,
    'title' => 'Command Area & Coastal Water Quality',
    'label' => 'withImage',
    'description' => 'Ensure water suitability for irrigation and protect coastal environments with specialized monitoring for command areas and coastal zones. In irrigation command areas, we monitor salinity, sodicity, nutrients, and contaminants that affect crop productivity and soil health.',
    'image' => 'upload/customer_services/nDuu9Vd8qeqKQ9eQqtSAjqUb7QpjUh9WLk4sVw1S.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  95 => 
  array (
    'id' => 186,
    'solution_id' => 129,
    'title' => 'Smart Irrigation Management',
    'label' => 'withImage',
    'description' => 'Conserve water and optimize crop health with intelligent irrigation systems that deliver exactly what your fields need, when they need it. Our solutions integrate soil moisture sensors, weather forecasts, evapotranspiration calculations, and crop water requirements.',
    'image' => 'upload/customer_services/ioXSODX4icm85Tj16VYMDQV19la444QlRweX3yZN.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  96 => 
  array (
    'id' => 187,
    'solution_id' => 129,
    'title' => 'Rainfall & Soil Moisture Monitoring',
    'label' => 'withImage',
    'description' => 'Make informed irrigation and planting decisions with precise rainfall and soil moisture monitoring at the field level. We deploy sensor networks that measure precipitation amounts, track soil moisture at multiple depths.',
    'image' => 'upload/customer_services/Bg3kKaFjN6sq5PpiGYq32eto7MFYGR2MeKTp79cv.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  97 => 
  array (
    'id' => 188,
    'solution_id' => 129,
    'title' => 'Crop & Yield Decision Support Systems',
    'label' => 'withImage',
    'description' => 'Enhance agricultural productivity with intelligent decision support systems that analyze weather patterns, soil conditions, and crop development stages. Our platforms provide actionable recommendations.',
    'image' => 'upload/customer_services/L5WHPgsZhn5Pl6ja94fKJNLSyRkxgKmVbFH8BVS0.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  98 => 
  array (
    'id' => 189,
    'solution_id' => 130,
    'title' => 'Directed Evolution & Genetic Optimization',
    'label' => 'withImage',
    'description' => 'Accelerate natural selection to create superior strains through directed evolution and systematic genetic optimization. We employ iterative mutation, selection, and screening strategies to enhance desired traits—whether improving enzyme activity.',
    'image' => 'upload/customer_services/ttu7XytexaAVEKRzuVkWKvx9M76zmjln3sayQVuZ.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  99 => 
  array (
    'id' => 190,
    'solution_id' => 130,
    'title' => 'Metabolic Pathway Design',
    'label' => 'withImage',
    'description' => 'Redesign cellular metabolism to maximize production of target compounds through intelligent metabolic pathway engineering. We use computational modeling, flux balance analysis, and systems biology approaches to identify bottlenecks, eliminate competing pathways.',
    'image' => 'upload/customer_services/xi3DQMVYEQr9TnVf0alFfMbEIDlJp4VFosLAsgId.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  100 => 
  array (
    'id' => 191,
    'solution_id' => 130,
    'title' => 'DNA Synthesis & Recombineering Platforms',
    'label' => 'withImage',
    'description' => 'Build and modify genomes with precision using advanced DNA synthesis and recombineering technologies. We provide custom gene synthesis, construct assembly, and genome editing services using CRISPR/Cas systems.',
    'image' => 'upload/customer_services/1so7uHIeLSSHV7sQ1YUb7L9xwWr3ppK8O0bbLvMp.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  101 => 
  array (
    'id' => 192,
    'solution_id' => 131,
    'title' => 'Media Formulation & Parameter Optimization',
    'label' => 'withImage',
    'description' => 'Maximize fermentation performance through systematic media formulation and process parameter optimization. We design and test nutrient compositions, carbon and nitrogen sources, trace elements, and growth factors tailored to your specific strain and product.',
    'image' => 'upload/customer_services/lCFP2gcmKFohqdMY0k4hFtAUXFk3ntjJqVyUpCoF.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  102 => 
  array (
    'id' => 193,
    'solution_id' => 131,
    'title' => 'Lab-to-Pilot Scale Up (5L→150L Bioreactors)',
    'label' => 'withImage',
    'description' => 'De-risk commercialization with systematic scale-up from laboratory benchtop to pilot-scale bioreactors. We transition your process from 5L to 150L systems while maintaining performance characteristics and product quality.',
    'image' => 'upload/customer_services/nmBdIPCumTDmZ63368kEIsVVusVeLXCpSk3FnD6C.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  103 => 
  array (
    'id' => 194,
    'solution_id' => 131,
    'title' => 'Scale-up Transfer for Production',
    'label' => 'withImage',
    'description' => 'Ensure smooth technology transfer to manufacturing facilities with comprehensive scale-up documentation and validation support. We prepare detailed process descriptions, batch records, risk assessments, and control strategies.',
    'image' => 'upload/customer_services/Bqv3pKqtKU6VbHaCRMksDbeazWZrfWogWhUUIrqo.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  104 => 
  array (
    'id' => 195,
    'solution_id' => 132,
    'title' => 'Biomass Separation (Filtration, Centrifugation)',
    'label' => 'withImage',
    'description' => 'Efficiently separate cells and biomass from fermentation broth using optimized filtration and centrifugation technologies.',
    'image' => 'upload/customer_services/Zg4R1XtOWZLJsdz8MUQUiOnYR5WkNe92hkeXIHSM.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  105 => 
  array (
    'id' => 196,
    'solution_id' => 132,
    'title' => 'Extraction & Purification (Chromatography, HPLC)',
    'label' => 'withImage',
    'description' => 'Achieve target purity specifications through expertly designed extraction and chromatographic purification strategies.',
    'image' => 'upload/customer_services/f4xzrD6IX3N7FV0fFMT3gJoQz4zvwEHPRtY2mRtj.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  106 => 
  array (
    'id' => 197,
    'solution_id' => 132,
    'title' => 'Analytical QA for Bioproducts',
    'label' => 'withImage',
    'description' => 'Ensure product quality and consistency with comprehensive analytical quality assurance testing throughout downstream processing.',
    'image' => 'upload/customer_services/52w89GKqe2mah5qHmpEk1YQh3JRnGEZFCbtw06UK.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  107 => 
  array (
    'id' => 198,
    'solution_id' => 133,
    'title' => 'Pilot-to-Production Transition',
    'label' => 'withImage',
    'description' => 'Navigate the critical transition from pilot scale to commercial manufacturing with expert guidance and comprehensive support.',
    'image' => 'upload/customer_services/g0MgbEhAdcCtrk3F4oJ3li8MLUuiuYzvuzlmusBz.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  108 => 
  array (
    'id' => 199,
    'solution_id' => 133,
    'title' => 'Process Optimization for Cost & Efficiency',
    'label' => 'withImage',
    'description' => 'Maximize profitability and competitiveness through systematic process optimization focused on cost reduction and operational efficiency. ',
    'image' => 'upload/customer_services/Ur8bTqEmk3dQ6agwL3wn0vHRqW7oiERL2ssZHxs9.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  109 => 
  array (
    'id' => 200,
    'solution_id' => 133,
    'title' => 'Industrial Biomanufacturing Support',
    'label' => 'withImage',
    'description' => 'Maintain production excellence with ongoing technical support and troubleshooting for industrial biomanufacturing operations.',
    'image' => 'upload/customer_services/N8M5BjZClysiCPCN04dh4uIEnK30MhNou2qFvtdT.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  110 => 
  array (
    'id' => 201,
    'solution_id' => 134,
    'title' => 'Agro-genomics, Sequencing & Food Testing',
    'label' => 'withImage',
    'description' => 'Unlock genetic insights and ensure food safety with comprehensive agro-genomics, DNA sequencing, and food testing services.',
    'image' => 'upload/customer_services/zqBvvNfnbRpMSNynLcdMCjH8wOyP0TL86f61cZQs.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  111 => 
  array (
    'id' => 202,
    'solution_id' => 134,
    'title' => 'Soil & Water Analysis / Industrial Effluent Treatment',
    'label' => 'withImage',
    'description' => 'Protect environmental health and ensure regulatory compliance with thorough soil, water, and industrial effluent analysis services.',
    'image' => 'upload/customer_services/lVgyvHh5YVKgGjPKnXcodiVNVuTa7QayImi9w1Z7.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  112 => 
  array (
    'id' => 203,
    'solution_id' => 134,
    'title' => 'Laboratory Equipment, Analytical Instruments, Kits & Reagents',
    'label' => 'withImage',
    'description' => 'Equip your laboratory with premium instruments, consumables, and reagents from leading global manufacturers. We supply complete solutions including molecular biology equipment, and chromatography systems.',
    'image' => 'upload/customer_services/u7stUcPUoQBoiq1OhfzaPXOoUHxg2ic6l5vsM4X6.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  113 => 
  array (
    'id' => 204,
    'solution_id' => 135,
    'title' => 'APIs, Vitamins, Food Colorants, Specialty Biochemicals',
    'label' => 'withImage',
    'description' => 'Develop and commercialize high-value bioproducts spanning pharmaceutical, nutritional, and specialty chemical markets.',
    'image' => 'upload/customer_services/Tsx5dOXgVKv3PvzGNSfH3LYM8RfRFkphbCBayCBh.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  114 => 
  array (
    'id' => 205,
    'solution_id' => 135,
    'title' => 'Collaboration with Global Partners for R&D and Manufacturing',
    'label' => 'withImage',
    'description' => 'Accelerate innovation and reduce development risks through strategic partnerships with world-class research institutions and contract manufacturing organizations (CMOs).',
    'image' => 'upload/customer_services/LB3WslFqh0mx6wePRX7DcOCiQej2R3EXzkxmL1Xy.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  115 => 
  array (
    'id' => 206,
    'solution_id' => 136,
    'title' => 'Site & Sunlight Analysis',
    'label' => 'withImage',
    'description' => 'Make informed investment decisions with comprehensive site assessment and solar resource analysis. We conduct detailed feasibility studies including solar irradiation measurement, shading analysis, topographic surveys, geotechnical investigations, and environmental assessments.',
    'image' => 'upload/customer_services/mPLtYw2ytZCHzSa4AkrY5L49ukgSZeMX3DlFqtG2.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  116 => 
  array (
    'id' => 207,
    'solution_id' => 136,
    'title' => 'PV System Design & Engineering',
    'label' => 'withImage',
    'description' => 'Transform solar potential into practical, high-performing photovoltaic systems through expert design and engineering.',
    'image' => 'upload/customer_services/N27jbsINkfZjLAWafX13deozQstderjW1v21DdBK.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  117 => 
  array (
    'id' => 208,
    'solution_id' => 136,
    'title' => 'Construction & Project Management',
    'label' => 'withImage',
    'description' => 'Execute solar projects flawlessly with experienced construction teams and rigorous project management.',
    'image' => 'upload/customer_services/yGhbT442TmB0lfEGDZ1AUglkHTY18HUW64zTZ9dl.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  118 => 
  array (
    'id' => 209,
    'solution_id' => 136,
    'title' => 'Grid Interconnection & Testing',
    'label' => 'withImage',
    'description' => 'Complete your solar project with seamless grid connection and comprehensive commissioning testing.',
    'image' => 'upload/customer_services/NpNgsSapqx5D1BeoReQ2SCqFo7zR1WfAvVZ0BOMa.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  119 => 
  array (
    'id' => 210,
    'solution_id' => 137,
    'title' => 'Remote System Monitoring & Analytics',
    'label' => 'withImage',
    'description' => 'Maximize energy production and catch issues early with comprehensive remote monitoring and intelligent analytics platforms.',
    'image' => 'upload/customer_services/jVm23NCeLhjvQGqRJJJc5ZSS0TpqiJkQ9mo2B1bw.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  120 => 
  array (
    'id' => 211,
    'solution_id' => 137,
    'title' => 'Preventive / Corrective Maintenance Programs',
    'label' => 'withImage',
    'description' => 'Protect your investment and ensure peak performance with comprehensive preventive and corrective maintenance programs tailored to your renewable energy systems.',
    'image' => 'upload/customer_services/CuyJn3vpDFAUloDmVeUMcSSeJwhQzCkOmwV3kcDY.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  121 => 
  array (
    'id' => 212,
    'solution_id' => 138,
    'title' => 'Physical Security Information Management (PSIM)',
    'label' => 'withImage',
    'description' => 'Unify fragmented security systems with PSIM platforms that integrate surveillance, access control, intrusion detection, fire alarms, and building systems into single management interfaces.',
    'image' => 'upload/customer_services/exVJvZJcjoLmj6GNXcIuouWBMvbT3ysy0GuraUpv.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  122 => 
  array (
    'id' => 213,
    'solution_id' => 138,
    'title' => 'Video Management Systems (VMS)',
    'label' => 'withImage',
    'description' => 'Manage surveillance infrastructure comprehensively with enterprise video management platforms that control cameras, recordings, analytics, and viewing across organizations.',
    'image' => 'upload/customer_services/Hgy2sie5UosSxL2ekkQTHnpNNSMsab9GvpcpQPJx.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  123 => 
  array (
    'id' => 214,
    'solution_id' => 138,
    'title' => 'Security Operations Center (SOC) Design',
    'label' => 'withImage',
    'description' => 'Create purpose-built command centers optimized for security monitoring and incident response.',
    'image' => 'upload/customer_services/iJOOd86rw6fhzUmdjD06lIZWB6CoMd5Use635xds.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  124 => 
  array (
    'id' => 215,
    'solution_id' => 138,
    'title' => 'Incident Management & Response Systems',
    'label' => 'withImage',
    'description' => 'Streamline security response with comprehensive incident management platforms that guide operators through detection, assessment, response, and resolution.',
    'image' => 'upload/customer_services/38hmXCXp1cyPXqxrHK77uLpw8kBXtLPSvALmD5W1.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  125 => 
  array (
    'id' => 216,
    'solution_id' => 139,
    'title' => 'IP Video Surveillance Systems',
    'label' => 'withImage',
    'description' => 'Deploy enterprise-grade IP camera networks that deliver crystal-clear visibility across your entire facility or campus.',
    'image' => 'upload/customer_services/USJZhX5IreVTVYb8BstcKIPY4fUaEm3iLbLLMqt1.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  126 => 
  array (
    'id' => 217,
    'solution_id' => 139,
    'title' => 'AI-Powered Video Analytics',
    'label' => 'withImage',
    'description' => 'Transform passive surveillance into proactive security with artificial intelligence that analyzes video in real-time.',
    'image' => 'upload/customer_services/uT7jeYv2hvf9krZCpRwcmmwkBA2xC8Et5HygmM59.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  127 => 
  array (
    'id' => 218,
    'solution_id' => 139,
    'title' => 'Command & Control Centers',
    'label' => 'withImage',
    'description' => 'Centralize security operations with integrated command and control centers that provide comprehensive situational awareness.',
    'image' => 'upload/customer_services/ZuU6fBw2QJwEjqP8gF35H8q7hYEoVTZMdNr4FZPJ.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  128 => 
  array (
    'id' => 219,
    'solution_id' => 139,
    'title' => 'Perimeter Security & Detection',
    'label' => 'withImage',
    'description' => 'Protect boundaries and critical zones with intelligent perimeter security systems that detect and deter intrusions before they reach sensitive areas.',
    'image' => 'upload/customer_services/mf3VflNNdYyaTzgKFHb3IQwAZLGEMaf4mFDCGQJ0.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  129 => 
  array (
    'id' => 220,
    'solution_id' => 140,
    'title' => 'Card-Based Access Systems',
    'label' => 'withImage',
    'description' => 'Secure facilities efficiently with card-based access control systems that provide convenient yet reliable authentication. We deploy systems using proximity cards, smart cards, or mobile credentials that grant access based on predefined permissions and schedules.',
    'image' => 'upload/customer_services/aIOc5wZlYC6BlvALfXoAUwyLeqDCtKRBzdzpXfX9.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  130 => 
  array (
    'id' => 221,
    'solution_id' => 140,
    'title' => 'Biometric Authentication Systems',
    'label' => 'withImage',
    'description' => 'Eliminate credential sharing and ensure positive identification with biometric access control using fingerprint, facial recognition, iris scanning, or palm vein technology.',
    'image' => 'upload/customer_services/buzmZwT9cPQN0NLmAT1cpRpQHVeUtqdEkbSrlnrP.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  131 => 
  array (
    'id' => 222,
    'solution_id' => 140,
    'title' => 'Time & Attendance Integration',
    'label' => 'withImage',
    'description' => 'Streamline workforce management by integrating access control with time and attendance tracking. Our unified solutions capture employee entry and exit automatically.',
    'image' => 'upload/customer_services/TpIM4TEFP1rY31lSbLy0XLf4pxacQ1Ug2Tw2E136.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  132 => 
  array (
    'id' => 223,
    'solution_id' => 140,
    'title' => 'Mobile Access & Cloud Solutions',
    'label' => 'withImage',
    'description' => 'Embrace modern access control with mobile credentials and cloud-based management platforms that offer flexibility and convenience.',
    'image' => 'upload/customer_services/jzMsGN0B8vERwl5JxGszW7EPnK8tDvFpGlrSCuzM.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  133 => 
  array (
    'id' => 224,
    'solution_id' => 141,
    'title' => 'Perimeter Intrusion Detection Systems',
    'label' => 'withImage',
    'description' => 'Secure your boundaries with advanced perimeter intrusion detection systems that create invisible security barriers around your property.',
    'image' => 'upload/customer_services/gt43YnbIIcheKobDPb7QzogiBWeNea9aUiGA3vJl.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  134 => 
  array (
    'id' => 225,
    'solution_id' => 141,
    'title' => 'Indoor Intrusion Alarm Systems',
    'label' => 'withImage',
    'description' => 'Protect interior spaces with comprehensive intrusion alarm systems that detect unauthorized entry into buildings and restricted areas.',
    'image' => 'upload/customer_services/PowLLqxFUt32rj7n5zqDN06EPUJZvLgKXJSFunyN.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  135 => 
  array (
    'id' => 226,
    'solution_id' => 141,
    'title' => 'Thermal & Radar Detection Systems',
    'label' => 'withImage',
    'description' => 'Achieve superior perimeter security in challenging conditions with thermal imaging and radar detection technologies.',
    'image' => 'upload/customer_services/DAk6PGCLPaE09FcK4bV4R9TZRWYOZmD044ztjF7E.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  136 => 
  array (
    'id' => 227,
    'solution_id' => 142,
    'title' => 'Addressable Fire Alarm Systems',
    'label' => 'withImage',
    'description' => 'Deploy intelligent fire detection with fully addressable alarm systems that pinpoint fire locations instantly. Our addressable systems assign unique identifiers to each detector and device, providing exact fire location information that speeds response and evacuation.',
    'image' => 'upload/customer_services/ySXjSDq0d8iByaPYQSxqRgiPgqtLB1xCdcwsIhFJ.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  137 => 
  array (
    'id' => 228,
    'solution_id' => 142,
    'title' => 'Smoke & Heat Detection Networks',
    'label' => 'withImage',
    'description' => 'Protect occupants and property with comprehensive smoke and heat detection networks strategically positioned throughout facilities. ',
    'image' => 'upload/customer_services/xIHALhaJDRGkgH42N7uLYiKCluFv0I758nyV4h1O.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  138 => 
  array (
    'id' => 229,
    'solution_id' => 142,
    'title' => 'Emergency Voice Evacuation Systems',
    'label' => 'withImage',
    'description' => 'Guide safe evacuations with intelligible voice communication systems that provide clear instructions during emergencies.',
    'image' => 'upload/customer_services/wecsd1VAzeyNw4e7qmx7VXLm28x0G7X1Z2hefLJF.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  139 => 
  array (
    'id' => 230,
    'solution_id' => 143,
    'title' => 'Campus & Facility-Wide PA Systems',
    'label' => 'withImage',
    'description' => 'Reach every corner of your facility with comprehensive public address systems designed for clear, consistent coverage.',
    'image' => 'upload/customer_services/6Jc1wo3VX2juQpkIUezIM4JS0VaMp3NlV9tqmm1E.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  140 => 
  array (
    'id' => 231,
    'solution_id' => 143,
    'title' => 'Emergency Mass Notification Systems',
    'label' => 'withImage',
    'description' => 'Protect lives with emergency mass notification systems that deliver critical alerts instantly across facilities.',
    'image' => 'upload/customer_services/pfpYPQ7YAh6hhOdYHCmgz6RMbRWwvwzxPIjYmV7v.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  141 => 
  array (
    'id' => 232,
    'solution_id' => 143,
    'title' => 'Conference Room & Boardroom Solutions',
    'label' => 'withImage',
    'description' => 'Transform meeting spaces with professional audio-visual systems that enable productive collaboration and impressive presentations.',
    'image' => 'upload/customer_services/3fvzywEEIhueHPi2tHI9ekPdAarVDAabU493cWtN.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  142 => 
  array (
    'id' => 233,
    'solution_id' => 143,
    'title' => 'Lecture Halls & Auditorium Systems',
    'label' => 'withImage',
    'description' => 'Deliver exceptional audio experiences in large venues with acoustically-optimized sound reinforcement and presentation systems.',
    'image' => 'upload/customer_services/mcbo53wGatpakMLg0phMldQKQK21zNSGPKkCjeD2.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  143 => 
  array (
    'id' => 234,
    'solution_id' => 144,
    'title' => 'X-Ray Baggage & Parcel Scanners',
    'label' => 'withImage',
    'description' => 'Inspect bags, packages, and cargo with advanced X-ray screening systems that reveal concealed threats and contraband.',
    'image' => 'upload/customer_services/d0fYWQee4kWcOgkDU4wd0PPG7Hs1ZgDxZCbib23J.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  144 => 
  array (
    'id' => 235,
    'solution_id' => 144,
    'title' => 'Walk-Through & Hand-Held Metal Detectors',
    'label' => 'withImage',
    'description' => 'Detect metallic weapons and prohibited items with reliable metal detection systems designed for high-volume screening.',
    'image' => 'upload/customer_services/j5ZfQTxMOUGVKtiEirQBsMBu229g3ZUlPqWhFJeb.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  145 => 
  array (
    'id' => 236,
    'solution_id' => 144,
    'title' => 'Explosive Trace Detection (ETD) Systems',
    'label' => 'withImage',
    'description' => 'Identify explosive materials and narcotics with ultra-sensitive trace detection technology that analyzes microscopic particles.',
    'image' => 'upload/customer_services/5j6yQGlEgcsZLKbm9kLZ3xHjI1EC7fmcazJYDQNh.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  146 => 
  array (
    'id' => 237,
    'solution_id' => 145,
    'title' => 'GPS Fleet Tracking Systems',
    'label' => 'withImage',
    'description' => 'Monitor your entire fleet in real-time with GPS tracking systems that provide complete visibility into vehicle locations, movements, and status.',
    'image' => 'upload/customer_services/B1ubdP504Q4tp2SBPGcabgKkFNgMNh3eDknXK0Pf.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  147 => 
  array (
    'id' => 238,
    'solution_id' => 145,
    'title' => 'Driver Behavior & Safety Monitoring',
    'label' => 'withImage',
    'description' => 'Improve safety and reduce insurance costs with comprehensive driver behavior monitoring and coaching systems.',
    'image' => 'upload/customer_services/V8m1zTPWNMEpP8Hpdd7kjLv0xyQ6Q3GrDWAd6IYp.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  148 => 
  array (
    'id' => 239,
    'solution_id' => 145,
    'title' => 'Maintenance Management & Diagnostics',
    'label' => 'withImage',
    'description' => 'Prevent breakdowns and extend vehicle life with predictive maintenance systems powered by telematics data.',
    'image' => 'upload/customer_services/eZR7PTxTopQNZQOhCJgSdiuzHaNzC7WONmwZhqPp.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  149 => 
  array (
    'id' => 240,
    'solution_id' => 145,
    'title' => 'Asset Protection & Recovery',
    'label' => 'withImage',
    'description' => 'Protect high-value vehicles and equipment with advanced security features and rapid recovery capabilities.',
    'image' => 'upload/customer_services/ErvOW0Y4DeA8upxzHL1ScRnK5b8jOj1AStAcRVAJ.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  150 => 
  array (
    'id' => 241,
    'solution_id' => 146,
    'title' => 'Geophysical Surveys & Exploration',
    'label' => 'withImage',
    'description' => 'Reveal subsurface geological structures and mineral deposits with comprehensive geophysical survey programs.',
    'image' => 'upload/customer_services/O9wOn3XiKhyoZnTrEiOmfege5OCqEjKEa35gOTaI.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  151 => 
  array (
    'id' => 242,
    'solution_id' => 146,
    'title' => 'Remote Sensing & Satellite Imagery Analysis',
    'label' => 'withImage',
    'description' => 'Leverage space-based technology for regional exploration and geological mapping using multispectral and hyperspectral remote sensing.',
    'image' => 'upload/customer_services/5uI9ysIbIN43ojK3tsyBDYlh5QOmovGSetCIDLkq.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  152 => 
  array (
    'id' => 243,
    'solution_id' => 146,
    'title' => 'Geological Mapping & Field Surveys',
    'label' => 'withImage',
    'description' => 'Build comprehensive geological understanding through systematic field mapping and surface investigations.',
    'image' => 'upload/customer_services/YWAcb68WJXTjPJentlYFl9zvGcONGaH0aWPnDpwT.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  153 => 
  array (
    'id' => 244,
    'solution_id' => 146,
    'title' => 'Geochemical Analysis & Soil Sampling',
    'label' => 'withImage',
    'description' => 'Detect mineralization footprints and pathfinder elements through systematic geochemical surveys and laboratory analysis.',
    'image' => 'upload/customer_services/y6yoUyWaOb27FzSdfMofZXXintQ2WJ47AGxBTn7i.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  154 => 
  array (
    'id' => 245,
    'solution_id' => 146,
    'title' => '3D Geological Modeling & Resource Estimation',
    'label' => 'withImage',
    'description' => 'Transform survey data into comprehensive 3D geological models that visualize subsurface conditions and support resource calculations.',
    'image' => 'upload/customer_services/TEp9f36O6NZMS4VYDsKcObeUGXdp4O616igO6KTi.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  155 => 
  array (
    'id' => 246,
    'solution_id' => 147,
    'title' => 'Autonomous Haulage & Fleet Management',
    'label' => 'withImage',
    'description' => 'Maximize productivity and safety with autonomous haul truck systems that operate 24/7 without human drivers.',
    'image' => 'upload/customer_services/U75z3LriwUata3ZDZkgq2FZX9YBEdLIm1tq7HiZ4.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  156 => 
  array (
    'id' => 247,
    'solution_id' => 147,
    'title' => 'Remote Equipment Operation Centers',
    'label' => 'withImage',
    'description' => 'Enhance safety and operational efficiency by controlling mining equipment remotely from surface control centers. ',
    'image' => 'upload/customer_services/R7mG7jFBq2ZJ689s3pBR035UybXfzRToYwQrHX1b.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  157 => 
  array (
    'id' => 248,
    'solution_id' => 147,
    'title' => 'Process Control & Plant Automation',
    'label' => 'withImage',
    'description' => 'Optimize mineral processing with advanced automation and control systems that maximize recovery, throughput, and efficiency.',
    'image' => 'upload/customer_services/KT0Rp1KvsbstNDaAuqr352ATbbpzoAshxyqFXxvM.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  158 => 
  array (
    'id' => 249,
    'solution_id' => 147,
    'title' => 'Production Monitoring & Analytics',
    'label' => 'withImage',
    'description' => 'Gain complete operational visibility with real-time production monitoring systems and advanced analytics platforms.',
    'image' => 'upload/customer_services/lCKV3JsDs5GOMFoRy2lQEDFVwCDTAxuG0n0kSNnJ.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  159 => 
  array (
    'id' => 250,
    'solution_id' => 147,
    'title' => 'Ventilation & Environmental Control Systems',
    'label' => 'withImage',
    'description' => 'Ensure safe underground conditions with automated ventilation control systems that optimize air quality while minimizing energy costs.',
    'image' => 'upload/customer_services/nO3kbcJsva0pdbO7HtDP2q3NilSEa27Sa3kLa0CM.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  160 => 
  array (
    'id' => 251,
    'solution_id' => 148,
    'title' => 'Real-Time Process Monitoring & SCADA',
    'label' => 'withImage',
    'description' => 'Gain complete operational visibility with real-time process monitoring systems integrating data from crushers, mills, flotation circuits, and downstream processes.',
    'image' => 'upload/customer_services/Ko4YXYyrEQJ4qz4b65zW2LtyiQNo5tmNITC2PuGe.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  161 => 
  array (
    'id' => 252,
    'solution_id' => 148,
    'title' => 'Metallurgical Accounting & Mass Balance Systems',
    'label' => 'withImage',
    'description' => 'Ensure accurate production reporting and identify process losses with sophisticated metallurgical accounting systems performing real-time mass and grade balancing.',
    'image' => 'upload/customer_services/K0d6HIgFbayoQxIznPJcvSlfHgtL2DEYpRK3m3qS.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  162 => 
  array (
    'id' => 253,
    'solution_id' => 148,
    'title' => 'Performance Analytics & Reporting Platforms',
    'label' => 'withImage',
    'description' => 'Drive continuous improvement with comprehensive analytics platforms that transform processing data into strategic insights.',
    'image' => 'upload/customer_services/ocj7BsApuJqAAQNuuuHyzWmpqQK5qivyfiS4FP8z.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  163 => 
  array (
    'id' => 254,
    'solution_id' => 149,
    'title' => 'Air Quality & Dust Monitoring',
    'label' => 'withImage',
    'description' => 'Protect worker health and community relations with comprehensive air quality and dust monitoring systems. ',
    'image' => 'upload/customer_services/IwDpzK6UvGMHEBEcKAhhf1KOmXHE82TYAVWeKm2Y.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  164 => 
  array (
    'id' => 255,
    'solution_id' => 149,
    'title' => 'Gas Detection & Atmospheric Monitoring',
    'label' => 'withImage',
    'description' => 'Ensure underground safety with real-time gas detection systems monitoring oxygen, methane, carbon monoxide, nitrogen dioxide, and other atmospheric hazards.',
    'image' => 'upload/customer_services/fuy76wVkHGrvr44wx4HrXKAyvZzr2bQretBSNuv0.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  165 => 
  array (
    'id' => 256,
    'solution_id' => 149,
    'title' => 'Ground Movement & Slope Stability Monitoring',
    'label' => 'withImage',
    'description' => 'Prevent catastrophic failures with sophisticated ground movement and slope stability monitoring using precision instruments and advanced analytics.',
    'image' => 'upload/customer_services/yjLQKllPsS4mtcIi1mugln3W7rXKFMjHCxVEkIDH.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  166 => 
  array (
    'id' => 257,
    'solution_id' => 149,
    'title' => 'Water Quality & Discharge Monitoring',
    'label' => 'withImage',
    'description' => 'Demonstrate environmental responsibility with comprehensive water quality monitoring across mine sites and discharge points. ',
    'image' => 'upload/customer_services/KpxMpTY0406QJvlFzboQsAxWF1QQMT5qN9UXC4T6.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  167 => 
  array (
    'id' => 258,
    'solution_id' => 149,
    'title' => 'Noise, Vibration & Blast Monitoring',
    'label' => 'withImage',
    'description' => 'Maintain community relations and regulatory compliance through systematic noise, vibration, and blast monitoring programs.',
    'image' => 'upload/customer_services/EusBSCIpdQAVUYCI1mkqlK1ByWVpE2da7UDrCYSa.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  168 => 
  array (
    'id' => 259,
    'solution_id' => 151,
    'title' => 'Financial Feasibility & ROI Modelling',
    'label' => 'withImage',
    'description' => 'Make confident renewable energy investments with rigorous financial feasibility analysis and return-on-investment modeling. We develop detailed financial models incorporating capital costs, operating expenses, energy production forecasts, electricity rates, incentives, tax benefits, and financing structures.',
    'image' => 'upload/customer_services/fOFZDjBxAcmgdDynI8VlT0HAyAtGB5ED2pUf5AdE.png',
    'deleted_at' => '2025-11-27 04:45:26',
    'created_at' => NULL,
    'updated_at' => '2025-11-27 04:45:26',
  ),
  169 => 
  array (
    'id' => 260,
    'solution_id' => 151,
    'title' => 'Corporate Sustainability Roadmaps',
    'label' => 'withImage',
    'description' => 'Chart your path to carbon neutrality and sustainability leadership with comprehensive corporate sustainability roadmaps.',
    'image' => 'upload/customer_services/ob7UFezkXwYV43cRoVzrOgLPgoRZZbXpAsE36ibn.png',
    'deleted_at' => '2025-11-27 04:45:26',
    'created_at' => NULL,
    'updated_at' => '2025-11-27 04:45:26',
  ),
  170 => 
  array (
    'id' => 261,
    'solution_id' => 151,
    'title' => 'Financial Feasibility & ROI Modelling',
    'label' => 'withImage',
    'description' => 'Make confident renewable energy investments with rigorous financial feasibility analysis and return-on-investment modeling.',
    'image' => 'upload/customer_services/d6L79bvCWBlhE9DTiJOhs8Nee07j6mEkVqeQNhRu.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  171 => 
  array (
    'id' => 262,
    'solution_id' => 151,
    'title' => 'Corporate Sustainability Roadmaps',
    'label' => 'withImage',
    'description' => 'Chart your path to carbon neutrality and sustainability leadership with comprehensive corporate sustainability roadmaps.',
    'image' => 'upload/customer_services/7LZmhbxw7NpbqKzXRghy4JeROTNqZl00WzJdhidw.png',
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  172 => 
  array (
    'id' => 263,
    'solution_id' => 150,
    'title' => 'Grid-Tied & Off-Grid Systems',
    'label' => 'withImage',
    'description' => 'Power your operations with flexible solar solutions designed for both grid-connected and remote applications. Our grid-tied systems reduce electricity bills through net metering, provide energy independence,',
    'image' => NULL,
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  173 => 
  array (
    'id' => 264,
    'solution_id' => 150,
    'title' => 'Industrial / Commercial Solar Plants',
    'label' => 'withImage',
    'description' => 'Reduce operational costs and enhance sustainability with large-scale solar installations for industrial facilities and commercial enterprises.',
    'image' => NULL,
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  174 => 
  array (
    'id' => 265,
    'solution_id' => 150,
    'title' => 'Telecom Solar Systems',
    'label' => 'withImage',
    'description' => 'Ensure uninterrupted telecommunications with reliable solar power systems designed for critical infrastructure.',
    'image' => NULL,
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
  175 => 
  array (
    'id' => 266,
    'solution_id' => 150,
    'title' => 'Agricultural / Irrigation Solar Solutions',
    'label' => 'withImage',
    'description' => 'Transform agricultural operations with solar-powered irrigation systems that reduce costs and increase farming flexibility. Our agricultural solutions power water pumps for irrigation, livestock watering, and farm operations',
    'image' => NULL,
    'deleted_at' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
  ),
);
        DB::table('customer_services')->insert($data);
    }
}
