/**
 * seed.js  –  AUTO-GENERATED by capture-seed.js
 * Generated at: 2026-05-06T05:06:35.250Z
 * Records: 1 users | 0 speakers | 2 topics | 0 lectures
 *
 * Run this seeder:
 *   npx prisma db seed
 */

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {

  // ── Users ─────────────────────────────────────────────────────
  // Note: passwords are already bcrypt-hashed – no re-hashing needed.

  await prisma.user.upsert({
    where:  { email: "admin@ilmhub.com" },
    update: {},
    create: {
      name:            "Admin",
      email:           "admin@ilmhub.com",
      password:        "$2b$12$i9y/CpS3ikYGHfnhaGoMl.TTvaSd4y9.Nr1eUWS4PDSZ1XCgBEudi",   // already hashed
      role:            "admin",
    },
  });

  // ── Speakers ──────────────────────────────────────────────────


  // ── Topics ────────────────────────────────────────────────────

  await prisma.topic.upsert({
    where:  { name: "Spirituality" },
    update: {},
    create: { name: "Spirituality" },
  });

  await prisma.topic.upsert({
    where:  { name: "History" },
    update: {},
    create: { name: "History" },
  });

  // ── Lectures (must come after speakers + topics) ──────────────


  console.log('✅ Seeding complete!');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
